### ISSUE TITLE
Cannot use this with Microsoft Fabric

### ISSUE THREAD

**Issue by alexanderfa24** [dbt-labs/dbt_faker#29]
Hi 
It seems the generate_faker_model only works with Snowflake, can you advise if there will be a release compatible with other dwh's such as Microsoft Fabric?

**Comment by Victoriapm** [comment]
Hi @alexanderfa24 , sorry for the very delayed response! 
The dbt-faker package relies on dbt Python models, and unfortunately there is no way to run a dbt Python model in a Microsoft platform at the moment (see supported platforms [here](https://docs.getdbt.com/docs/build/python-models#specific-data-platforms)).

Cheers

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
